services:
  app:
    image: beasticn/projet-laravel-app:1.0.1
    volumes:
      - ../../PhpstormProjects/PROJET-LARAVEL:/var/www
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: craftedby
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
